# Generated by Django 4.0.6 on 2022-07-16 06:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('petrolpumpApp', '0002_fueltype_supplier_tanker_machine_fuel'),
    ]

    operations = [
        migrations.CreateModel(
            name='FuelVehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_reg_no', models.CharField(max_length=10)),
                ('vehicle_name', models.CharField(max_length=50)),
                ('vehicle_type', models.CharField(max_length=20)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='petrolpumpApp.customer')),
            ],
        ),
        migrations.CreateModel(
            name='FuelServiceStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station_name', models.CharField(default='', max_length=100)),
                ('email', models.CharField(default='', max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('ss_phone', models.CharField(max_length=12)),
                ('stat_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FuelService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_of_fuel', models.CharField(max_length=50, null=True)),
                ('fuel_qua', models.IntegerField(default=1)),
                ('ser_status', models.CharField(choices=[('Waiting', 'Waiting'), ('In progress', 'In progress'), ('Completed', 'Completed')], max_length=100, null=True)),
                ('start_date', models.DateTimeField(null=True)),
                ('finish_date', models.DateTimeField(null=True)),
                ('ser', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='petrolpumpApp.fuelservicestation')),
                ('ss', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='petrolpumpApp.customer')),
                ('veh', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='petrolpumpApp.fuelvehicle')),
            ],
        ),
    ]
