# Generated by Django 4.0.6 on 2022-07-29 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('petrolpumpApp', '0005_admincustomer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tanker',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='petrolpumpApp.supplier'),
        ),
    ]
