# Generated by Django 4.0.6 on 2022-07-30 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petrolpumpApp', '0006_alter_tanker_supplier'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pic/CustomerProfilePic/'),
        ),
    ]
