# Generated by Django 4.0.6 on 2022-07-30 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('petrolpumpApp', '0007_customer_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='avatar',
        ),
    ]
