# Generated by Django 4.0.6 on 2022-08-01 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petrolpumpApp', '0009_profilepic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fuelservice',
            name='type_of_fuel',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='fuelvehicle',
            name='vehicle_type',
            field=models.CharField(max_length=10000),
        ),
    ]
