# Generated by Django 4.0.6 on 2022-08-01 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petrolpumpApp', '0010_alter_fuelservice_type_of_fuel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='service_desc',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
