# Generated by Django 4.0.6 on 2022-08-05 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petrolpumpApp', '0011_alter_service_service_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fuelservice',
            name='start_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='start_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
